### ISSUE TITLE
Audio playback is silent when running the .NET MAUI Blazor app on iPhone

### ISSUE THREAD

**Issue by MackinnonBuck** [microsoft/dotnet-podcasts#123]
When attempting to play a podcast on iPhone, no sound comes out. Attempting to skip ahead throws the following exception:

```
Nullable object must have a value.
at System.Nullable`1[[System.Double, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].get_Value()
at Podcast.Components.Player.FloatingPlayer.Forward() in C:\dotnet-podcasts\src\Web\Components\Player\FloatingPlayer.razor:line 166
at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync[Object](MulticastDelegate , Object )
at Microsoft.AspNetCore.Components.EventCallbackWorkItem.InvokeAsync(Object )
at Microsoft.AspNetCore.Components.ComponentBase.Microsoft.AspNetCore.Components.IHandleEvent.HandleEventAsync(EventCallbackWorkItem callback, Object arg)
at Microsoft.AspNetCore.Components.EventCallback.InvokeAsync(Object )
at Microsoft.AspNetCore.Components.RenderTree.Renderer.DispatchEventAsync(UInt64 , EventFieldInfo , EventArgs )
```

**Steps to reproduce:**

* Run the backend locally with Docker
* Run the MobileBlazor app on either an iPhone simulator or physical iPhone (tested with physical iPhone XR and iPhone 11 simulator)
* Try playing a podcast
* Click the "skip ahead" button, which will throw an exception and make the entire app uninteractive until restarted

**Expected result:**

Audio plays, and skipping ahead works as expected

**Actual result:**

No audio plays, and clicking the "skip ahead" button makes the app uninteractive until restarted

**Notes:**

I've tested on the iPad Air (5th generation) simulator, and it does **not** exhibit the same problem (audio playback works as expected). The iPad simulator, iPhone simulator, and physical iPhone were all running iOS 15.4.

**Comment by antborari** [comment]
Tested on iPhone simulator.
Can you try this branch?
https://github.com/microsoft/dotnet-podcasts/tree/feature/fix-error-blazor-audio-oncanplay

I have tested on Iphone SE (2nd generation) 14.2 simulator and it works correctly.
