### ISSUE TITLE
In docker dotnet-podcasts-podcast.api-1 cannot run

### ISSUE THREAD

**Issue by pccai** [microsoft/dotnet-podcasts#183]
2022-12-02 13:29:03 Unhandled exception. Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
2022-12-02 13:29:03  ---> System.Security.Authentication.AuthenticationException: The remote certificate was rejected by the provided RemoteCertificateValidationCallback.
2022-12-02 13:29:03    at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
2022-12-02 13:29:03    at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
2022-12-02 13:29:03    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](Boolean receiveFirst, Byte[] reAuthenticationData, CancellationToken cancellationToken)
2022-12-02 13:29:03    at System.Net.Security.SslStream.AuthenticateAsClient(SslClientAuthenticationOptions sslClientAuthenticationOptions)
2022-12-02 13:29:03    at Microsoft.Data.SqlClient.SNI.SNITCPHandle.EnableSsl(UInt32 options)

**Comment by pccai** [comment]
2022-12-02 13:29:03 --- End of stack trace from previous location ---
2022-12-02 13:29:03    at Microsoft.EntityFrameworkCore.SqlServer.Storage.Internal.SqlServerExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)
2022-12-02 13:29:03    at Microsoft.EntityFrameworkCore.Migrations.HistoryRepository.ExistsAsync(CancellationToken cancellationToken)
2022-12-02 13:29:03    at Microsoft.EntityFrameworkCore.Migrations.Internal.Migrator.MigrateAsync(String targetMigration, CancellationToken cancellationToken)
2022-12-02 13:29:03    at Program.<<Main>$>g__EnsureDbAsync|0_10(IServiceProvider sp) in /src/src/Services/Podcasts/Podcast.API/Program.cs:line 193
2022-12-02 13:29:03    at Program.<<Main>$>g__EnsureDbAsync|0_10(IServiceProvider sp) in /src/src/Services/Podcasts/Podcast.API/Program.cs:line 193
2022-12-02 13:29:03    at Program.<Main>$(String[] args) in /src/src/Services/Podcasts/Podcast.API/Program.cs:line 130
2022-12-02 13:29:03    at Program.<Main>(String[] args)
2022-12-02 13:29:03 ClientConnectionId:284c3e05-9985-4385-b7c1-69d98fae4e65
2022-12-02 13:29:03 Error Number:-2146893019,State:0,Class:20

**Comment by pccai** [comment]
Windows 10, Docker Desktop v4.15.0

**Comment by jamesmontemagno** [comment]
i'll pull it down today fresh and give it a look
