### ISSUE TITLE
Podcasts app crashes -> NullReferenceException => solution Disable XAML Hot Reload in Tools->Options

### ISSUE THREAD

**Issue by bartvanhoey** [microsoft/dotnet-podcasts#22]
I watched the [.NET Podcasts app - Local Development Walkthrough](https://www.youtube.com/watch?v=FJowBj-DBgI) video on Youtube. When I tried to run the .NET Maui app on my mobile phone, the app threw a NullReferenceException.

After checking the Device Log I found it had something to do with XAML Hot Reload.  After disabling XAML Hot Reload in Tools->Options in Visual Studio 2022 Preview, I could run the Podcasts app.

DEVICE LOG
01-07 22:55:41.354	pixel_2_pie_9_0_-_api_28	Error	6645	mono-rt	[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
   at Xamarin.HotReload.Xaml.VisualTreeService.DiagnosticVisualTreeService.Dispose(Boolean isDisposing) in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Xaml\VisualTreeService\DiagnosticVisualTreeService.cs:line 75
   at Xamarin.HotReload.Xaml.VisualTreeService.VisualTreeService.Finalize() in D:\a\_work\1\s\HotReload\Source\Xamarin.HotReload.Xaml\VisualTreeService\VisualTreeService.cs:line 138

**Comment by jamesmontemagno** [comment]
#23 fixes this currently. Some other odd issues, but I'll pull it in atleast
